### ISSUE TITLE
Example code for running Rankers on MS-Marco Passage Reranking dataset

### ISSUE THREAD

**Issue by skmalviya** [davidmrau/rankers#1]
Hi,
Thanks for integrating many rankers in one repo!

I was curious to run some of the rankers on MS-Marco Passage Reranking dataset. Could you provide a sample code using this repo on  [MS-Marco Passage Reranking dataset](https://microsoft.github.io/msmarco/Datasets.html#passage-ranking-dataset).

**Comment by davidmrau** [comment]
Hi, you can find an example of adding new datasets in the README I provided:

## Adding a new Test Dataset:
New datasets with their respective file paths can be added in datasets.json and loaded using --dataset_test new_dataset. In our example case this would be new_dataset. Test Datasets follow the format:
```python
{
	{ "test":
		"new_dataset": 
			"qrels": "qrels_path",
			"trec_run": "trec_run_path",
			"queries": "queries_path",
			"docs": "doc_path",
		
	}
}
```
Basically you need to download the qrels, the reference trec run that you want to re-rank, a file containing the queries, and a file containing the documents and link them in the dataset.json file to the corresponding path. you can find example configurations in the dataset.json file. 


To re-rank you can use then the following command: 

```python

python3 run.py \
	--model 'CrossEncoder' \
	--dataset_test 'example' \
	--max_inp_len 512 \
	--mb_size_test 128 \
	--exp_dir '/tmp/example/'

```

**Comment by skmalviya** [comment]
Hi, thank you for showing the right direction with example codes. 
I am still struggling with it running on the [MS-Marco Passage Reranking dataset](https://microsoft.github.io/msmarco/Datasets.html#passage-ranking-dataset).

The main reason I can observe is the input data format:

[Example](https://github.com/davidmrau/rankers/tree/master/examples) data format:
 	&nbsp;&nbsp;&nbsp;&nbsp; **Docs**: p_id, passage 
	&nbsp;&nbsp;&nbsp;&nbsp; **Queries**: q_id, query
	&nbsp;&nbsp;&nbsp;&nbsp; **Qrels**: q_id, 0, p_id 0
	&nbsp;&nbsp;&nbsp;&nbsp; **Trec_run**: q_id, Q_0, p_id

[MS-Marco Passage Reranking](https://microsoft.github.io/msmarco/Datasets.html#passage-ranking-dataset) data format:
 	&nbsp;&nbsp;&nbsp;&nbsp; **Docs**: p_id, passage 
	&nbsp;&nbsp;&nbsp;&nbsp; **Queries**: q_id, query
	&nbsp;&nbsp;&nbsp;&nbsp; **Qrels**:  q_id, 0, p_id, 1 
	&nbsp;&nbsp;&nbsp;&nbsp; **Top1000**: q_id, p_id, query, passage  

I am sure setting up the right parameters may resolve the issue. Or changing the format, especially the 4th file in the data, can also help. I can't figure this out. Can you help me get through this problem?



**Note:** I ran the following statement:

```
python run.py --model CrossEncoder --dataset_test msmarco_passage_ranking --max_inp_len 512 --mb_size_test 128 --exp_dir /tmp/msmarco_passage_ranking
```

with **"--dataset_test msmarco_passage_ranking"** pointing to dataset below:
 	&nbsp;&nbsp;&nbsp;&nbsp; **Docs**: [collection.tar.gz](https://msmarco.blob.core.windows.net/msmarcoranking/collection.tar.gz)
	&nbsp;&nbsp;&nbsp;&nbsp; **Queries**: [queries.tar.gz](https://msmarco.blob.core.windows.net/msmarcoranking/queries.tar.gz)
	&nbsp;&nbsp;&nbsp;&nbsp; **Qrels**:  [qrels.dev.tsv](https://msmarco.blob.core.windows.net/msmarcoranking/qrels.dev.tsv) 
	&nbsp;&nbsp;&nbsp;&nbsp; **Top1000**: [top1000.dev.tar.gz](https://msmarco.blob.core.windows.net/msmarcoranking/top1000.dev.tar.gz)

**Comment by davidmrau** [comment]
Hey, you should unpack the docs, queries, and top1000 runs first. If you have done this, can you please provide your error message?

**Comment by skmalviya** [comment]
I've saved the log output linked below:
[Log.zip](https://github.com/davidmrau/rankers/files/12301295/Log.zip)

It ran successfully. But the accuracy was 0.0, with lots of "word" not found.
![image](https://github.com/davidmrau/rankers/assets/19930752/5a94d231-f302-48d0-afc8-1ed61ebf4c3e)

Data directory:
![image](https://github.com/davidmrau/rankers/assets/19930752/01dd7a75-e1fc-4232-a894-a23b45051998)

**Comment by davidmrau** [comment]
could you also provide your `msmarco_passage_ranking` configuration in the `datasets.json`

**Comment by skmalviya** [comment]
```
    "test": {
        "msmarco_passage_reranking": {
            "qrels": "data/msmarco/qrels.dev.tsv",
            "trec_run": "data/msmarco/top1000.dev",
            "queries": "data/msmarco/queries.dev.tsv",
            "docs": "data/msmarco/collection.tsv"
            }
      }
```

**Comment by davidmrau** [comment]
Ok, I see now. Indeed the problem is the format of the top-1000 file. Which is expected to be in the trec format. I would suggest you convert it into the following tab-separated format: qid Q0 did

**Comment by davidmrau** [comment]
You could do this with the following command: 

```bash
awk '{print $1"\tQ0\t"$2}' top1000.dev > top1000.dev.trec
```

**Comment by skmalviya** [comment]
Ok, got it! I thought that I was not doing it the right way.
```
awk '{print $1"\tQ0\t"$2}' top1000.dev > top1000.dev.trec
```
The [above statement](https://github.com/davidmrau/rankers/issues/1#issuecomment-1671115210) really a time-saving.

**Comment by davidmrau** [comment]
You did everything right ;)
